version: '3.8'

services:
  ski-project:
    image: medaminer/ski-project
    ports:
      - "9091:9091"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-container:3306/SkiStationDB?createDatabaseIfNotExist=true
    networks:
      - test_default