version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - volume-test:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    container_name: prometheus_Monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    container_name: grafana_Monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data: